package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Mar 18, 2014 9:13:36 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NmDevice generated by hbm2java
 */
public class NmDevice  implements java.io.Serializable {


     private Integer id;
     private String deviceName;
     private String deviceDescription;
     private String ipv4Address;
     private Date modifiedDate;
     private Date createDate;
     private Set nmProbes = new HashSet(0);

    public NmDevice() {
    }

	
    public NmDevice(String deviceName, String ipv4Address, Date createDate) {
        this.deviceName = deviceName;
        this.ipv4Address = ipv4Address;
        this.createDate = createDate;
    }
    public NmDevice(String deviceName, String deviceDescription, String ipv4Address, Date modifiedDate, Date createDate, Set nmProbes) {
       this.deviceName = deviceName;
       this.deviceDescription = deviceDescription;
       this.ipv4Address = ipv4Address;
       this.modifiedDate = modifiedDate;
       this.createDate = createDate;
       this.nmProbes = nmProbes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDeviceName() {
        return this.deviceName;
    }
    
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }
    public String getDeviceDescription() {
        return this.deviceDescription;
    }
    
    public void setDeviceDescription(String deviceDescription) {
        this.deviceDescription = deviceDescription;
    }
    public String getIpv4Address() {
        return this.ipv4Address;
    }
    
    public void setIpv4Address(String ipv4Address) {
        this.ipv4Address = ipv4Address;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Set getNmProbes() {
        return this.nmProbes;
    }
    
    public void setNmProbes(Set nmProbes) {
        this.nmProbes = nmProbes;
    }




}


