package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Apr 5, 2014 4:21:51 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * NmDevice generated by hbm2java
 */
@Entity
@Table(name = "nm_device", catalog = "stuba_netmonitor"
)
public class NmDevice implements java.io.Serializable {

    private Integer id;
    private String deviceName;
    private String deviceDescription;
    private String ipv4Address;
    private Date modifiedDate;
    private Date createDate;
    private Set nmProbes = new HashSet(0);

    public NmDevice() {
    }

    public NmDevice(String deviceName, String ipv4Address, Date createDate) {
        this.deviceName = deviceName;
        this.ipv4Address = ipv4Address;
        this.createDate = createDate;
    }

    public NmDevice(String deviceName, String deviceDescription, String ipv4Address, Date modifiedDate, Date createDate, Set nmProbes) {
        this.deviceName = deviceName;
        this.deviceDescription = deviceDescription;
        this.ipv4Address = ipv4Address;
        this.modifiedDate = modifiedDate;
        this.createDate = createDate;
        this.nmProbes = nmProbes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "device_name", nullable = false)
    public String getDeviceName() {
        return this.deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    @Column(name = "device_description", length = 65535)
    public String getDeviceDescription() {
        return this.deviceDescription;
    }

    public void setDeviceDescription(String deviceDescription) {
        this.deviceDescription = deviceDescription;
    }

    @Column(name = "ipv4_address", nullable = false, length = 15)
    public String getIpv4Address() {
        return this.ipv4Address;
    }

    public void setIpv4Address(String ipv4Address) {
        this.ipv4Address = ipv4Address;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "modified_date", length = 19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = javax.persistence.CascadeType.ALL, orphanRemoval = true)
    @NotFound(action = NotFoundAction.IGNORE)
    public Set getNmProbes() {
        return this.nmProbes;
    }

    public void setNmProbes(Set nmProbes) {
        this.nmProbes = nmProbes;
    }

}
