package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Apr 5, 2014 4:21:51 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NmInterfaceStats generated by hbm2java
 */
@Entity
@Table(name="nm_interface_stats"
    ,catalog="stuba_netmonitor"
)
public class NmInterfaceStats  implements java.io.Serializable {


     private Integer id;
     private NmInterface nmInterface;
     private int interfaceAdminStatus;
     private int interfaceOperationalStatus;
     private long interfaceRxBytes;
     private long interfaceTxBytes;
     private long interfaceRxPackets;
     private long interfaceTxPackets;
     private long interfaceRxDiscardsDrops;
     private long interfaceTxDiscardsDrops;
     private Date createDate;

    public NmInterfaceStats() {
    }

    public NmInterfaceStats(NmInterface nmInterface, int interfaceAdminStatus, int interfaceOperationalStatus, long interfaceRxBytes, long interfaceTxBytes, long interfaceRxPackets, long interfaceTxPackets, long interfaceRxDiscardsDrops, long interfaceTxDiscardsDrops, Date createDate) {
       this.nmInterface = nmInterface;
       this.interfaceAdminStatus = interfaceAdminStatus;
       this.interfaceOperationalStatus = interfaceOperationalStatus;
       this.interfaceRxBytes = interfaceRxBytes;
       this.interfaceTxBytes = interfaceTxBytes;
       this.interfaceRxPackets = interfaceRxPackets;
       this.interfaceTxPackets = interfaceTxPackets;
       this.interfaceRxDiscardsDrops = interfaceRxDiscardsDrops;
       this.interfaceTxDiscardsDrops = interfaceTxDiscardsDrops;
       this.createDate = createDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="interface_id", nullable=false)
    public NmInterface getNmInterface() {
        return this.nmInterface;
    }
    
    public void setNmInterface(NmInterface nmInterface) {
        this.nmInterface = nmInterface;
    }

    
    @Column(name="interface_admin_status", nullable=false)
    public int getInterfaceAdminStatus() {
        return this.interfaceAdminStatus;
    }
    
    public void setInterfaceAdminStatus(int interfaceAdminStatus) {
        this.interfaceAdminStatus = interfaceAdminStatus;
    }

    
    @Column(name="interface_operational_status", nullable=false)
    public int getInterfaceOperationalStatus() {
        return this.interfaceOperationalStatus;
    }
    
    public void setInterfaceOperationalStatus(int interfaceOperationalStatus) {
        this.interfaceOperationalStatus = interfaceOperationalStatus;
    }

    
    @Column(name="interface_rx_bytes", nullable=false)
    public long getInterfaceRxBytes() {
        return this.interfaceRxBytes;
    }
    
    public void setInterfaceRxBytes(long interfaceRxBytes) {
        this.interfaceRxBytes = interfaceRxBytes;
    }

    
    @Column(name="interface_tx_bytes", nullable=false)
    public long getInterfaceTxBytes() {
        return this.interfaceTxBytes;
    }
    
    public void setInterfaceTxBytes(long interfaceTxBytes) {
        this.interfaceTxBytes = interfaceTxBytes;
    }

    
    @Column(name="interface_rx_packets", nullable=false)
    public long getInterfaceRxPackets() {
        return this.interfaceRxPackets;
    }
    
    public void setInterfaceRxPackets(long interfaceRxPackets) {
        this.interfaceRxPackets = interfaceRxPackets;
    }

    
    @Column(name="interface_tx_packets", nullable=false)
    public long getInterfaceTxPackets() {
        return this.interfaceTxPackets;
    }
    
    public void setInterfaceTxPackets(long interfaceTxPackets) {
        this.interfaceTxPackets = interfaceTxPackets;
    }

    
    @Column(name="interface_rx_discards_drops", nullable=false)
    public long getInterfaceRxDiscardsDrops() {
        return this.interfaceRxDiscardsDrops;
    }
    
    public void setInterfaceRxDiscardsDrops(long interfaceRxDiscardsDrops) {
        this.interfaceRxDiscardsDrops = interfaceRxDiscardsDrops;
    }

    
    @Column(name="interface_tx_discards_drops", nullable=false)
    public long getInterfaceTxDiscardsDrops() {
        return this.interfaceTxDiscardsDrops;
    }
    
    public void setInterfaceTxDiscardsDrops(long interfaceTxDiscardsDrops) {
        this.interfaceTxDiscardsDrops = interfaceTxDiscardsDrops;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


