package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Apr 5, 2014 4:21:51 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NmInterfaceAggregatedStats generated by hbm2java
 */
@Entity
@Table(name="nm_interface_aggregated_stats"
    ,catalog="stuba_netmonitor"
)
public class NmInterfaceAggregatedStats  implements java.io.Serializable {


     private Integer id;
     private NmProbe nmProbe;
     private int interfaceCount;
     private long rxBytes;
     private long txBytes;
     private long rxPackets;
     private long txPackets;
     private Date createDate;

    public NmInterfaceAggregatedStats() {
    }

    public NmInterfaceAggregatedStats(NmProbe nmProbe, int interfaceCount, long rxBytes, long txBytes, long rxPackets, long txPackets, Date createDate) {
       this.nmProbe = nmProbe;
       this.interfaceCount = interfaceCount;
       this.rxBytes = rxBytes;
       this.txBytes = txBytes;
       this.rxPackets = rxPackets;
       this.txPackets = txPackets;
       this.createDate = createDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="probe_id", nullable=false)
    public NmProbe getNmProbe() {
        return this.nmProbe;
    }
    
    public void setNmProbe(NmProbe nmProbe) {
        this.nmProbe = nmProbe;
    }

    
    @Column(name="interface_count", nullable=false)
    public int getInterfaceCount() {
        return this.interfaceCount;
    }
    
    public void setInterfaceCount(int interfaceCount) {
        this.interfaceCount = interfaceCount;
    }

    
    @Column(name="rx_bytes", nullable=false)
    public long getRxBytes() {
        return this.rxBytes;
    }
    
    public void setRxBytes(long rxBytes) {
        this.rxBytes = rxBytes;
    }

    
    @Column(name="tx_bytes", nullable=false)
    public long getTxBytes() {
        return this.txBytes;
    }
    
    public void setTxBytes(long txBytes) {
        this.txBytes = txBytes;
    }

    
    @Column(name="rx_packets", nullable=false)
    public long getRxPackets() {
        return this.rxPackets;
    }
    
    public void setRxPackets(long rxPackets) {
        this.rxPackets = rxPackets;
    }

    
    @Column(name="tx_packets", nullable=false)
    public long getTxPackets() {
        return this.txPackets;
    }
    
    public void setTxPackets(long txPackets) {
        this.txPackets = txPackets;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


