package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Mar 18, 2014 9:13:36 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * NmInterfaceStats generated by hbm2java
 */
public class NmInterfaceStats implements java.io.Serializable {

    private Integer id;
    private NmInterface nmInterface;
    private int interfaceAdminStatus;
    private int interfaceOperationalStatus;
    private long interfaceRxBytes;
    private long interfaceTxBytes;
    private long interfaceRxPackets;
    private long interfaceTxPackets;
    private long interfaceRxDiscardsDrops;
    private long interfaceTxDiscardsDrops;
    private Date createDate;

    public NmInterfaceStats() {
    }

    public NmInterfaceStats(NmInterface nmInterface, int interfaceAdminStatus, int interfaceOperationalStatus, long interfaceRxBytes, long interfaceTxBytes, long interfaceRxPackets, long interfaceTxPackets, long interfaceRxDiscardsDrops, long interfaceTxDiscardsDrops, Date createDate) {
        this.nmInterface = nmInterface;
        this.interfaceAdminStatus = interfaceAdminStatus;
        this.interfaceOperationalStatus = interfaceOperationalStatus;
        this.interfaceRxBytes = interfaceRxBytes;
        this.interfaceTxBytes = interfaceTxBytes;
        this.interfaceRxPackets = interfaceRxPackets;
        this.interfaceTxPackets = interfaceTxPackets;
        this.interfaceRxDiscardsDrops = interfaceRxDiscardsDrops;
        this.interfaceTxDiscardsDrops = interfaceTxDiscardsDrops;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public NmInterface getNmInterface() {
        return this.nmInterface;
    }

    public void setNmInterface(NmInterface nmInterface) {
        this.nmInterface = nmInterface;
    }

    public int getInterfaceAdminStatus() {
        return this.interfaceAdminStatus;
    }

    public void setInterfaceAdminStatus(int interfaceAdminStatus) {
        this.interfaceAdminStatus = interfaceAdminStatus;
    }

    public int getInterfaceOperationalStatus() {
        return this.interfaceOperationalStatus;
    }

    public void setInterfaceOperationalStatus(int interfaceOperationalStatus) {
        this.interfaceOperationalStatus = interfaceOperationalStatus;
    }

    public long getInterfaceRxBytes() {
        return this.interfaceRxBytes;
    }

    public void setInterfaceRxBytes(long interfaceRxBytes) {
        this.interfaceRxBytes = interfaceRxBytes;
    }

    public long getInterfaceTxBytes() {
        return this.interfaceTxBytes;
    }

    public void setInterfaceTxBytes(long interfaceTxBytes) {
        this.interfaceTxBytes = interfaceTxBytes;
    }

    public long getInterfaceRxPackets() {
        return this.interfaceRxPackets;
    }

    public void setInterfaceRxPackets(long interfaceRxPackets) {
        this.interfaceRxPackets = interfaceRxPackets;
    }

    public long getInterfaceTxPackets() {
        return this.interfaceTxPackets;
    }

    public void setInterfaceTxPackets(long interfaceTxPackets) {
        this.interfaceTxPackets = interfaceTxPackets;
    }

    public long getInterfaceRxDiscardsDrops() {
        return this.interfaceRxDiscardsDrops;
    }

    public void setInterfaceRxDiscardsDrops(long interfaceRxDiscardsDrops) {
        this.interfaceRxDiscardsDrops = interfaceRxDiscardsDrops;
    }

    public long getInterfaceTxDiscardsDrops() {
        return this.interfaceTxDiscardsDrops;
    }

    public void setInterfaceTxDiscardsDrops(long interfaceTxDiscardsDrops) {
        this.interfaceTxDiscardsDrops = interfaceTxDiscardsDrops;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}
