package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Mar 18, 2014 9:13:36 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * NmInterfaceAggregatedStats generated by hbm2java
 */
public class NmInterfaceAggregatedStats implements java.io.Serializable {

    private Integer id;
    private NmProbe nmProbe;
    private int interfaceCount;
    private long rxBytes;
    private long txBytes;
    private long rxPackets;
    private long txPackets;
    private Date createDate;

    public NmInterfaceAggregatedStats() {
    }

    public NmInterfaceAggregatedStats(NmProbe nmProbe, int interfaceCount, long rxBytes, long txBytes, long rxPackets, long txPackets, Date createDaet) {
        this.nmProbe = nmProbe;
        this.interfaceCount = interfaceCount;
        this.rxBytes = rxBytes;
        this.txBytes = txBytes;
        this.rxPackets = rxPackets;
        this.txPackets = txPackets;
        this.createDate = createDaet;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public NmProbe getNmProbe() {
        return this.nmProbe;
    }

    public void setNmProbe(NmProbe nmProbe) {
        this.nmProbe = nmProbe;
    }

    public int getInterfaceCount() {
        return this.interfaceCount;
    }

    public void setInterfaceCount(int interfaceCount) {
        this.interfaceCount = interfaceCount;
    }

    public long getRxBytes() {
        return this.rxBytes;
    }

    public void setRxBytes(long rxBytes) {
        this.rxBytes = rxBytes;
    }

    public long getTxBytes() {
        return this.txBytes;
    }

    public void setTxBytes(long txBytes) {
        this.txBytes = txBytes;
    }

    public long getRxPackets() {
        return this.rxPackets;
    }

    public void setRxPackets(long rxPackets) {
        this.rxPackets = rxPackets;
    }

    public long getTxPackets() {
        return this.txPackets;
    }

    public void setTxPackets(long txPackets) {
        this.txPackets = txPackets;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDaet) {
        this.createDate = createDaet;
    }

}
