package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Mar 18, 2014 9:13:36 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * NmInterfaceAggregatedStats generated by hbm2java
 */
public class NmInterfaceAggregatedStats  implements java.io.Serializable {


     private Integer id;
     private NmProbe nmProbe;
     private int interfaceCount;
     private int rxBytesSec;
     private int txBytesSec;
     private int rxPacketsSec;
     private int txPacketsSec;
     private Date createDaet;

    public NmInterfaceAggregatedStats() {
    }

    public NmInterfaceAggregatedStats(NmProbe nmProbe, int interfaceCount, int rxBytesSec, int txBytesSec, int rxPacketsSec, int txPacketsSec, Date createDaet) {
       this.nmProbe = nmProbe;
       this.interfaceCount = interfaceCount;
       this.rxBytesSec = rxBytesSec;
       this.txBytesSec = txBytesSec;
       this.rxPacketsSec = rxPacketsSec;
       this.txPacketsSec = txPacketsSec;
       this.createDaet = createDaet;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public NmProbe getNmProbe() {
        return this.nmProbe;
    }
    
    public void setNmProbe(NmProbe nmProbe) {
        this.nmProbe = nmProbe;
    }
    public int getInterfaceCount() {
        return this.interfaceCount;
    }
    
    public void setInterfaceCount(int interfaceCount) {
        this.interfaceCount = interfaceCount;
    }
    public int getRxBytesSec() {
        return this.rxBytesSec;
    }
    
    public void setRxBytesSec(int rxBytesSec) {
        this.rxBytesSec = rxBytesSec;
    }
    public int getTxBytesSec() {
        return this.txBytesSec;
    }
    
    public void setTxBytesSec(int txBytesSec) {
        this.txBytesSec = txBytesSec;
    }
    public int getRxPacketsSec() {
        return this.rxPacketsSec;
    }
    
    public void setRxPacketsSec(int rxPacketsSec) {
        this.rxPacketsSec = rxPacketsSec;
    }
    public int getTxPacketsSec() {
        return this.txPacketsSec;
    }
    
    public void setTxPacketsSec(int txPacketsSec) {
        this.txPacketsSec = txPacketsSec;
    }
    public Date getCreateDaet() {
        return this.createDaet;
    }
    
    public void setCreateDaet(Date createDaet) {
        this.createDaet = createDaet;
    }




}


