package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Mar 18, 2014 9:13:36 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NmInterface generated by hbm2java
 */
public class NmInterface  implements java.io.Serializable {


     private Integer id;
     private NmProbe nmProbe;
     private int interfaceIndex;
     private String interfaceName;
     private String interfaceType;
     private Date lastUpdateDate;
     private Date createDate;
     private Set nmInterfaceStatses = new HashSet(0);

    public NmInterface() {
    }

	
    public NmInterface(NmProbe nmProbe, int interfaceIndex, String interfaceName, Date createDate) {
        this.nmProbe = nmProbe;
        this.interfaceIndex = interfaceIndex;
        this.interfaceName = interfaceName;
        this.createDate = createDate;
    }
    public NmInterface(NmProbe nmProbe, int interfaceIndex, String interfaceName, String interfaceType, Date lastUpdateDate, Date createDate, Set nmInterfaceStatses) {
       this.nmProbe = nmProbe;
       this.interfaceIndex = interfaceIndex;
       this.interfaceName = interfaceName;
       this.interfaceType = interfaceType;
       this.lastUpdateDate = lastUpdateDate;
       this.createDate = createDate;
       this.nmInterfaceStatses = nmInterfaceStatses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public NmProbe getNmProbe() {
        return this.nmProbe;
    }
    
    public void setNmProbe(NmProbe nmProbe) {
        this.nmProbe = nmProbe;
    }
    public int getInterfaceIndex() {
        return this.interfaceIndex;
    }
    
    public void setInterfaceIndex(int interfaceIndex) {
        this.interfaceIndex = interfaceIndex;
    }
    public String getInterfaceName() {
        return this.interfaceName;
    }
    
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }
    public String getInterfaceType() {
        return this.interfaceType;
    }
    
    public void setInterfaceType(String interfaceType) {
        this.interfaceType = interfaceType;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Set getNmInterfaceStatses() {
        return this.nmInterfaceStatses;
    }
    
    public void setNmInterfaceStatses(Set nmInterfaceStatses) {
        this.nmInterfaceStatses = nmInterfaceStatses;
    }




}


