package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Apr 5, 2014 4:21:51 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NmProbeStats generated by hbm2java
 */
@Entity
@Table(name = "nm_probe_stats", catalog = "stuba_netmonitor"
)
public class NmProbeStats implements java.io.Serializable {

    private Integer id;
    private NmProbe nmProbe;
    private String attributeName;
    private String attributeValue;
    private Date lastUpdateDate;

    public NmProbeStats() {
    }

    public NmProbeStats(NmProbe nmProbe, String attributeName, Date lastUpdateDate) {
        this.nmProbe = nmProbe;
        this.attributeName = attributeName;
        this.lastUpdateDate = lastUpdateDate;
    }

    public NmProbeStats(NmProbe nmProbe, String attributeName, String attributeValue, Date lastUpdateDate) {
        this.nmProbe = nmProbe;
        this.attributeName = attributeName;
        this.attributeValue = attributeValue;
        this.lastUpdateDate = lastUpdateDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "probe_identity_id", nullable = false)
    public NmProbe getNmProbe() {
        return this.nmProbe;
    }

    public void setNmProbe(NmProbe nmProbe) {
        this.nmProbe = nmProbe;
    }

    @Column(name = "attribute_name", nullable = false)
    public String getAttributeName() {
        return this.attributeName;
    }

    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    @Column(name = "attribute_value", length = 65535)
    public String getAttributeValue() {
        return this.attributeValue;
    }

    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_date", nullable = false, length = 19)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

}
