package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Mar 18, 2014 9:13:36 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NmProbe generated by hbm2java
 */
public class NmProbe  implements java.io.Serializable {


     private Integer id;
     private NmProbeType nmProbeType;
     private NmDevice nmDevice;
     private int probeStatus;
     private Date lastUpdateDate;
     private Date createDate;
     private Set nmProbeStatses = new HashSet(0);
     private Set nmInterfaces = new HashSet(0);
     private Set nmInterfaceAggregatedStatses = new HashSet(0);

    public NmProbe() {
    }

	
    public NmProbe(NmProbeType nmProbeType, NmDevice nmDevice, int probeStatus, Date createDate) {
        this.nmProbeType = nmProbeType;
        this.nmDevice = nmDevice;
        this.probeStatus = probeStatus;
        this.createDate = createDate;
    }
    public NmProbe(NmProbeType nmProbeType, NmDevice nmDevice, int probeStatus, Date lastUpdateDate, Date createDate, Set nmProbeStatses, Set nmInterfaces, Set nmInterfaceAggregatedStatses) {
       this.nmProbeType = nmProbeType;
       this.nmDevice = nmDevice;
       this.probeStatus = probeStatus;
       this.lastUpdateDate = lastUpdateDate;
       this.createDate = createDate;
       this.nmProbeStatses = nmProbeStatses;
       this.nmInterfaces = nmInterfaces;
       this.nmInterfaceAggregatedStatses = nmInterfaceAggregatedStatses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public NmProbeType getNmProbeType() {
        return this.nmProbeType;
    }
    
    public void setNmProbeType(NmProbeType nmProbeType) {
        this.nmProbeType = nmProbeType;
    }
    public NmDevice getNmDevice() {
        return this.nmDevice;
    }
    
    public void setNmDevice(NmDevice nmDevice) {
        this.nmDevice = nmDevice;
    }
    public int getProbeStatus() {
        return this.probeStatus;
    }
    
    public void setProbeStatus(int probeStatus) {
        this.probeStatus = probeStatus;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Set getNmProbeStatses() {
        return this.nmProbeStatses;
    }
    
    public void setNmProbeStatses(Set nmProbeStatses) {
        this.nmProbeStatses = nmProbeStatses;
    }
    public Set getNmInterfaces() {
        return this.nmInterfaces;
    }
    
    public void setNmInterfaces(Set nmInterfaces) {
        this.nmInterfaces = nmInterfaces;
    }
    public Set getNmInterfaceAggregatedStatses() {
        return this.nmInterfaceAggregatedStatses;
    }
    
    public void setNmInterfaceAggregatedStatses(Set nmInterfaceAggregatedStatses) {
        this.nmInterfaceAggregatedStatses = nmInterfaceAggregatedStatses;
    }




}


