package net.ctrdn.stuba.dbs.netmonitor.hbm;
// Generated Mar 18, 2014 9:13:36 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * NmProbeStats generated by hbm2java
 */
public class NmProbeStats  implements java.io.Serializable {


     private Integer id;
     private NmProbe nmProbe;
     private String attributeName;
     private String attributeValue;
     private Date lastUpdateDate;

    public NmProbeStats() {
    }

	
    public NmProbeStats(NmProbe nmProbe, String attributeName, Date lastUpdateDate) {
        this.nmProbe = nmProbe;
        this.attributeName = attributeName;
        this.lastUpdateDate = lastUpdateDate;
    }
    public NmProbeStats(NmProbe nmProbe, String attributeName, String attributeValue, Date lastUpdateDate) {
       this.nmProbe = nmProbe;
       this.attributeName = attributeName;
       this.attributeValue = attributeValue;
       this.lastUpdateDate = lastUpdateDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public NmProbe getNmProbe() {
        return this.nmProbe;
    }
    
    public void setNmProbe(NmProbe nmProbe) {
        this.nmProbe = nmProbe;
    }
    public String getAttributeName() {
        return this.attributeName;
    }
    
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }
    public String getAttributeValue() {
        return this.attributeValue;
    }
    
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }




}


